name: optimization_web_app

dependencies:
  - python=3.7
  - numpy
  - pip:
    - olymp==0.0.1b0
    - scikit-learn==1.0.2
    - matplotlib==3.5.1
    - seaborn==0.11.2
    - sqlalchemy==1.4.29
    - phoenics==0.2.0
    - silence-tensorflow==1.1.1
    - tensorflow-gpu
    - tensorflow-io-gcs-filesystem==0.23.1
    - tensorflow-probability==0.11
    - Flask==2.0.3
    - Flask-Mail==0.9.1
    
